### ISSUE TITLE
Vim marks are removed when switching sessions

### ISSUE THREAD

**Issue by bzgec** [Shatur/neovim-session-manager#100]
**Describe the problem or limitation you are having**
Vim marks are removed when switching sessions.

**Describe the solution you'd like**
I would like my previous marks to be restored when I switch sessions.

**Describe alternatives you've considered**
Instead of global marks I use [harpoon](https://github.com/ThePrimeagen/harpoon) to switch between files. There is also an option to have multiple harpoon marks per file - [ Multiple marks per file #139 ](https://github.com/ThePrimeagen/harpoon/issues/139). Harpoon solution addresses the issue of global marks for me, but the problem with buffer local marks still persists.

**Comment by Shatur** [comment]
We use `:mksession`. If `:mksession` does not save marks, then there is nothing we can do about it.
