### ISSUE TITLE
add print_last_session() and print_cwd_session()

### ISSUE THREAD

**Issue by simonlearnscoding** [Shatur/neovim-session-manager#102]
it would be nice if you could add a feature to get a string of the last session and the CWD session so I can display those with startup-nvim

**Comment by Shatur** [comment]
Current session is basically a cwd and last session is here:
https://github.com/Shatur/neovim-session-manager/blob/68dde355a4304d83b40cf073f53915604bdd8e70/lua/session_manager/utils.lua#L12
