### ISSUE TITLE
Strange conflicting with Neo-tree

### ISSUE THREAD

**Issue by allenfrostline** [Shatur/neovim-session-manager#106]
When having both session-manager and neo-tree installed (and opened), running `SessionManager save_current_session` (or using the corresponding keybinding) will collapse the neo-tree despite no keybinding conflict is observed.

Should be fairly easy to replicate.

**Comment by Shatur** [comment]
It's impossible to fix since I need to close all unsavable buffers before using `:mksession`.

**Comment by allenfrostline** [comment]
can you plz enlighten me a bit why closing buffers results in closing neotree here (still new to the nvim ecosystem)?

**Comment by Shatur** [comment]
Neotree is just a regular buffer provided by the plugin and I have to close it because I can't save it with `:mksession`.

**Comment by allenfrostline** [comment]
ouch that makes a lot sense. I agree with you now :headache:
