### ISSUE TITLE
CurrentDir not working for lazy nvim setup

### ISSUE THREAD

**Issue by aniketgm** [Shatur/neovim-session-manager#113]
**Bug description**
I'm using lazy.nvim, I've set the options for autoload_mode as `CurrentDir`, but when I open nvim in the folder, the session of current directory does not load. What am I doing wrong here ?

**Steps to reproduce**
This is my very simple config:
```lua
  {
    "Shatur/neovim-session-manager",
    dependencies = { "nvim-lua/plenary.nvim" },
    opts = {
      autoload_mode = require('session_manager.config').AutoloadMode.CurrentDir,
    }
  },
```
1. `cd` into the folder for which you already have session saved -- `cd <folder>`
2. Open neovim -- The session for this current folder does not open automatically. I have to manually open using `SessionManager load_current_dir_session`

**Expected behavior**
* When `cd` into the folder and open neovim, the session against the current folder should open automatically.

**Screenshots/Gif**

![wezterm-gui_9obxCSq5uF](https://github.com/Shatur/neovim-session-manager/assets/14215698/92a9dd92-ce7e-46b5-a880-ec1e933211fd)

**Environment**

- OS: Windows
- Desktop environment: NA
- Plugins commit hash: d8e1ba3bbcf3fdc6a887bcfbd94c48ae4707b457

**Additional context**
NA

**Comment by aniketgm** [comment]
LunarVim does not have any session by default. Just the "alpha-nvim" screen that can be seen in the gif that loads at startup.

**Comment by Shatur** [comment]
Yes, I suspect that the welcome screen could cause the issue.

**Comment by aniketgm** [comment]
Gif after disabling alpha-nvim: (Still issue is there. I think alpha-nvim is not the issue)

![wezterm-gui_Pr1PlurFxh](https://github.com/Shatur/neovim-session-manager/assets/14215698/7ea116c5-c634-49ae-9a52-16f6dff6840a)

**Comment by Shatur** [comment]
Weird. Can't reproduce the issue on my side with the exact same configuration. For me it loads the session from the current working directory from which I opened neovim...

I can only suggest to try disabling plugins and see if any plugin causes an issue.
Other possibility could be your packet manager. Maybe it loads the plugin too late and the session doesn't load up?
You can check it by placing the plugin in `~/.config/nvim/pack/plugins/start/` and put the following file as `~/.config/nvim/plugin/session_manager.lua`:
```lua
session_manager.setup({
  autoload_mode = require('session_manager.config').AutoloadMode.CurrentDir,
})
```

**Comment by aniketgm** [comment]
So, it seems setting `opts` does not work. Because, there I'm setting the options for the config beforehand. `opts is passed to config`. For packer, I believe the options are required to be set inside the setup. What lazy gives is flexibility to set options and call config around those.
But anyways, eventually, the following worked,
```lua
{
  "Shatur/neovim-session-manager",
  dependencies = { "nvim-lua/plenary.nvim" },
  config = function()
    require('session_manager').setup({
      autoload_mode = require('session_manager.config').AutoloadMode.CurrentDir,
    })
  end
},
```
