### ISSUE TITLE
`nvim-lspconfig.opts.autoformat` is deprecated. Please use `vim.g.autoformat` instead

### ISSUE THREAD

**Issue by grappas** [Shatur/neovim-session-manager#114]
**Bug description**
Not a bug but nice thing to have in back of your head. Need to be changed or add if statement for neovim version checking.

**Steps to reproduce**

Install this plugin in neovim nightly (>=0.10).

![obraz](https://github.com/Shatur/neovim-session-manager/assets/1036957/80fe2458-d561-45a8-9d3a-95efe19b830e)
![obraz](https://github.com/Shatur/neovim-session-manager/assets/1036957/fdbd3c00-d0d7-453c-98b0-fb5b99108106)

**Comment by Shatur** [comment]
Feel free to open a PR.

**Comment by grappas** [comment]
nah... sry. Stacktrace is dumb.
