### ISSUE TITLE
Neotest summary prevents session from being saved

### ISSUE THREAD

**Issue by orlandosh** [Shatur/neovim-session-manager#124]
**Bug description**
If you open neotest summary, even just once, it prevents the session from being saved.
It loads the previous session because it only rewrites it when quitting.

**Steps to reproduce**

<details><summary>Minimal configuration</summary>
1- Neotest

2- neovim-session-manager

Settings:
```lua
local Path = require("plenary.path")
require("session_manager").setup({
	sessions_dir = Path:new(vim.fn.stdpath("data"), "sessions"), -- The directory where the session files will be saved.
	path_replacer = "__", -- The character to which the path separator will be replaced for session files.
	colon_replacer = "++", -- The character to which the colon symbol will be replaced for session files.
	autoload_mode = require("session_manager.config").AutoloadMode.CurrentDir, -- Define what to do when Neovim is started without arguments. Possible values: Disabled, CurrentDir, LastSession
	autosave_last_session = true, -- Automatically save last session on exit and on session switch.
	autosave_ignore_not_normal = true, -- Plugin will not save a session when no buffers are opened, or all of them aren't writable or listed.
	autosave_ignore_filetypes = { -- All buffers of these file types will be closed before the session is saved.
		"gitcommit",
		"neotest-summary", -- same bug with or without it
	},
	autosave_only_in_session = false, -- Always autosaves session. If true, only autosaves after a session is active.
	max_path_length = 80, -- Shorten the display path if length exceeds this threshold. Use 0 if don't want to shorten the path at all.
})

```

</details>

Steps to reproduce:
1. `:Neotest summary`
2. open another file
3. `:wqa`
4. open neovim.
5. verify that the file you opened was not restored when you reopened nvim.

**Extra comments**
- I've tested locally adding "neotest-summary" to the list of ignored filetypes, does not change anything
- saving and sourcing manually in another path with mksession and source works normally

**Environment**

- OS: Fedora Rawhide
- Desktop environment: N/A (headless)
- Plugins commit hash: b552ee8667037be5d0291229279a35af25e515fb
- Nvim versions: tested with 0.11 nightly and 0.10 stable

**Comment by Shatur** [comment]
I believe that neotest is just not a regular buffer. We don't save such buffers because it's impossible.

**Comment by orlandosh** [comment]
Indeed, intentionally I've tried to close all neotest buffers as well before quitting, to see if the plugin works or anything changes, but it didn't.

I did quite some debugging with my basic nvim lua knowledge but I couldn't find the reason why the mksession executed from session_manager utils.save_session just rewrites the old session, ignoring changes (new buffers, closed buffers, etc) from the current session.

I'd love to help find out why, but my plugin development knowledge is very limited. Also, running mksession manually from the cmdline works fine as described.

My guess is that perhaps the way both handle file pointers might be conflicting, but I have no idea, I'm sorry.

**Comment by Shatur** [comment]
Wait, you mean that no only neotest buffers are ignored, but also regular buffers unsaved as well?

**Comment by orlandosh** [comment]
yes. if I open Neotest summary just once, for some reason, afterwards the session manager just keeps rewriting the previous session, while mksession from the cmdline works normally.

**Comment by Shatur** [comment]
What is your current directory when you trying to save session after opening the summary?

**Comment by orlandosh** [comment]
Hi @Shatur,

Currently, it happens in any directory, no matter the name or structure.
However, upon further investigation, I found out the same behavior happens with every other mksession wrapper, so, to me, it looks like an issue with Neotest. 

I will create a function to close everything related to Neotest and unload it before closing nvim to confirm it, later when I have time. However, I think this issue should be closed for now, as it's not a problem with your plugin.

Thank you so much for your work.
