### ISSUE TITLE
attempting to call field 'isarray' (a nil value)

### ISSUE THREAD

**Issue by simonlearnscoding** [Shatur/neovim-session-manager#129]
**Bug description**
<!-- A clear and concise description of what the bug is.

  local modes = config.autoload_mode
  if not vim.isarray(config.autoload_mode) then
    modes = { config.autoload_mode }
  end
  
  this line in the code gives me an error on startup. it seems vim.isarray is a nil value
  
  
**Steps to reproduce**
Neovim 0.95 on arch
This started happening after I just updated to the latest version of session-manager. I see that these lines of code were written a week ago

**Comment by Shatur** [comment]
Dup of #127.
