### ISSUE TITLE
After the latest update (29f80e9) getting auto command error

### ISSUE THREAD

**Issue by niksingh710** [Shatur/neovim-session-manager#131]
**Bug description**
After the latest update of commit `29f80e9` if running `nvim` only getting error
![image](https://github.com/Shatur/neovim-session-manager/assets/60490474/420e104e-21d8-401e-aa99-66dc4b3e7777)

**Steps to reproduce**
just do `nvim`

- OS: Arch Linux
- Desktop environment: Hyprland

**Comment by Shatur** [comment]
Duplicate of #127.
