### ISSUE TITLE
No syntax highlighting when loaded from `autocmd`

### ISSUE THREAD

**Issue by Bitals** [Shatur/neovim-session-manager#137]
**Bug description**
When I call `load_last_session` from an `autocmd`, I have no syntax highlighting in the first opened file for some reason.
If I later open a file in any other way, including inside this session, everything works. If I specify a file as an argument when opening, everything works. If I load another session and then reload the initial session, everything works. Just not from this function for some reason.

Config: https://github.com/Bitals/neovim-config/blob/b628864a8fe89b1be6183a4552af1f768f487837/init.lua#L54

**Steps to reproduce**
1. Save a session
2. Close and reopen Neovim
3. See error

**Expected behavior**
Syntax highlighting works

**Screenshots**
No highlights:
![image](https://github.com/user-attachments/assets/0e7347c1-1535-49ae-8dd5-41ede5a668a1)
Yes highlights:
![image](https://github.com/user-attachments/assets/2c7dff20-2b97-472e-a897-6dfe74441450)

**Environment**

- OS: Arch Linux
- Desktop environment: Gnome
- Plugins commit hash: `35c154a`

**Additional context**
Terminal: Alacritty

**Comment by Bitals** [comment]
As can be seen on the screenshots, not only `treesitter` is missing, but basically half of the plugins don't work in this scenario. For some reason `session-manager` (I assume) prevents nvim loading anything else when it is executed on event `VimEnter`

**Comment by Shatur** [comment]
Can't reproduce on my side.

**Comment by Bitals** [comment]
@Shatur with an `autocmd` on `VimEnter`?

**Comment by Shatur** [comment]
Yes, autoloading happens on `VimEnter` by default:
https://github.com/Shatur/neovim-session-manager/blob/35c154a4b904cbe2aa7acce00a8c1c54a8831780/plugin/session_manager.lua#L12

**Comment by Bitals** [comment]
@Shatur huh, right, sorry. But this way doesn't work for my workflow, but that is a confirmed me problem now.

**Comment by Shatur** [comment]
Check if some other plugin causes it.

**Comment by ankushbhagats** [comment]
Here I used autocmd fix that issue:

```lua
vim.api.nvim_create_autocmd("User", {
  pattern = "SessionLoadPost",
  callback = function()
    vim.cmd("filetype detect")
  end,
})
```
