### ISSUE TITLE
Session manager hijacks the man buffer

### ISSUE THREAD

**Issue by lostl1ght** [Shatur/neovim-session-manager#15]
**Bug description**

When using neovim as a man pager with enabled auto loading, plugin loads a session instead of a man page.

**Steps to reproduce**

Use these settings and then `man nvim`.

Plugin config:
```lua
require('session_manager').setup({
    autoload_mode = require('session_manager.config').AutoloadMode.CurrentDir
})
```
or
```lua
require('session_manager').setup({
    autoload_mode = require('session_manager.config').AutoloadMode.LastSession
})
```

.zshrc/.bashrc:
```bash
export MANPAGER='nvim -c Man!'
```

**Expected behavior**

I'd like to see a man page.

**Environment**

- OS: Manjaro Linux
- Desktop environment: Gnome
- Terminal: Alacritty
- Plugin's commit hash: 9e3dad0

**Additional context**

Probably exactly like [this](https://github.com/goolord/alpha-nvim/issues/44) issue. The dev also has a fix, although maybe there's a cleaner solution.

**Comment by Shatur** [comment]
Fixed, thanks!
