### ISSUE TITLE
Integration with fzf plugins

### ISSUE THREAD

**Issue by RaZ0rr-Two** [Shatur/neovim-session-manager#16]
**Describe the problem or limitation you are having**

Is there any plan to integrate with fzf plugins like [fzf-lua](https://github.com/ibhagwan/fzf-lua) or [fzf vim](https://github.com/junegunn/fzf.vim) for session picker

**Additional context**

Haven't used telescope yet as fzf has been sufficient

**Comment by Shatur** [comment]
I personally don't use FZF, but PR's are welcome.

**Comment by Shatur** [comment]
I think we should migrate to `vim.select` API. This will provide integration for any file picker plugin.

**Comment by Shatur** [comment]
Implemented in a97b8d0430ca41275e5670e4a92e3c1c979b78f2.

**Comment by RayZ0rr** [comment]
Thanks
