### ISSUE TITLE
autosave should have ignore filetype like "gitcommit"

### ISSUE THREAD

**Issue by xanahopper** [Shatur/neovim-session-manager#19]
I use nvim to code and edit commit message. when enable autosave session, current directory's session change to commit message edit which I don't want.

Maybe config should have some ignore filetype or situations like this?

**Comment by Shatur** [comment]
Although you ignored the template, I agree that it would be useful. I think it is worth adding the option `not_normal_filetypes` which will be used in with `autosave_ignore_not_normal` (maybe rename these two options?). And then just add additional check for this filetypes here:

https://github.com/Shatur/neovim-session-manager/blob/bff80bee884d7f728dd1030d7639a422475d5269/lua/session_manager/utils.lua#L124

I'm busy at the moment, but PR is welcome. @ranebrown you may be interested in this.
