### ISSUE TITLE
sessions should be saved automatically when switching between sessions

### ISSUE THREAD

**Issue by juantascon** [Shatur/neovim-session-manager#20]
**Bug description**

Sessions are not saved automatically when switching sessions using telescope

**Steps to reproduce**

1. use this config:

```
     require('session_manager').setup{
        autoload_mode = require('session_manager.config').AutoloadMode.CurrentDir,
        autosave_only_in_session = true,
      }
```

2. open vim from cwd dir1, open file1.2 and file1.2, run: :SaveSession and close vim
3. open vim from cwd dir2, open file2.1 and file2.2, run: :SaveSession and close vim
4. open vim again from dir1, the buffers (file1.1 and file1.2) are restored correctly
5. open a new file (file1.3) and now switch to session in dir2 by calling :Telescope sessions
6. switch back to session in dir1 again with telescope
7. only buffers file1.1 and file1.2 are restored but file1.3 from step 5. is not

**Expected behavior**
it should autosave when switching between sessions 

**Screenshots**

**Environment**

- OS: voidlinux
- Desktop environment: i3
- Plugins commit hash: bff80bee884d7f728dd1030d7639a422475d5269

**Additional context**

**Comment by Shatur** [comment]
Have you tried `:Telescope sessions save_current=true`?

**Comment by Shatur** [comment]
I assume that this was the case. Also after migration to `vim.ui.select()` from Telescope extension it's regulated by `autosave_last_session`. So it's enabled by default.
