### ISSUE TITLE
The document should be updated now

### ISSUE THREAD

**Issue by RnYi** [Shatur/neovim-session-manager#21]
I just find you can use `d` (in normal mode) to delete a session from Telescope` session picker. But this feature aren't described in README.

**Comment by Shatur** [comment]
It noted in [Commands](https://github.com/Shatur/neovim-session-manager#commands) table.

**Comment by Tej12345** [comment]
No it's not noted there. False statement.

**Comment by Shatur** [comment]
Because it was half of a year ago. We don't use `d` for delete now. We have `delete_session` subcommand.
