### ISSUE TITLE
Way to delete sessions

### ISSUE THREAD

**Issue by KodyVB** [Shatur/neovim-session-manager#22]
Is there any new way to delete sessions now that you've moved away from using `:Telescope sessions` and now use `SessionManager`, other than going to the sessions directory and manually deleting them? I'd previously just hover over the session in normal mode and use `d` to delete it, but that doesn't seem to be an option anymore.

**Comment by Shatur** [comment]
Yes, unfortunately I sacrificed this function to migrate to `vim.ui.select()`.
I could provide a separate command for session deletion. What do you think?

**Comment by KodyVB** [comment]
Seems like a decent solution to me - bringing up a list of the sessions via `vim.ui.select()` then iterating through all the selected sessions and deleting them would be nice in my opinion.

**Comment by tobealive** [comment]
@Shatur I didn't found a way to delete several sessions at once in the Deletion dialog. Is something like that possible?

**Comment by Shatur** [comment]
> @Shatur I didn't found a way to delete several sessions at once in the Deletion dialog. Is something like that possible?

This is not possible at the moment, because `vim.select` does not provide an API for selecting multiple objects.

**Comment by tobealive** [comment]
Roger that. Thanks a lot for the quick reply!

**Comment by KodyVB** [comment]
I opened [an issue](https://github.com/neovim/neovim/issues/17044) on the Neovim Github asking for multiple selections to be available back in January. Hopefully someone will pick it up eventually.

**Comment by tobealive** [comment]
#42 probably that does the job?
