### ISSUE TITLE
NvimTree open on session load

### ISSUE THREAD

**Issue by afreidz** [Shatur/neovim-session-manager#24]
**Describe the problem or limitation you are having**
presently when i switch/load sessions, nvimtree is closed by default causing me to have to re-open it any time i switch.

**Describe the solution you'd like**
it would be nice to have a hook into when a session is loaded such that i can call the nvimtree open command

**Describe alternatives you've considered**
some funky autocmd to run it on bufenter or something

**Comment by Shatur** [comment]
I think we could solve this by adding custom autocmd. Users will be able to call their own commends. I currently a little busy for now, but contribution is welcome.

**Comment by afreidz** [comment]
ill take a look and see if i can figure it out. a bit new to lua myself tho.

**Comment by Shatur** [comment]
Closed by #32.
