### ISSUE TITLE
`save_current_session` closes all terminal buffers even though not specified in `autosave_ignore_filetypes`

### ISSUE THREAD

**Issue by shawnyu5** [Shatur/neovim-session-manager#25]
**Bug description**

Saving a session via `:SessionManager save_current_session` will close all active terminal buffers, even though not specified in `autosave_ignore_filetypes`

**Steps to reproduce**
1. Open any file
2. Open a terminal session in a new tab
3. save current session

<details><summary>Minimal configuration</summary>

```
local Path = require("plenary.path")
session_manager.setup({
	sessions_dir = Path:new(vim.fn.stdpath("data"), "sessions"), -- The directory where the session files will be saved.
	path_replacer = "__", -- The character to which the path separator will be replaced for session files.
	colon_replacer = "++", -- The character to which the colon symbol will be replaced for session files.
	autoload_mode = require("session_manager.config").AutoloadMode.CurrentDir,
	-- Define what to do when Neovim is started without arguments. Possible
	-- values: Disabled, CurrentDir, LastSession
	autosave_last_session = false, -- Automatically save last session on exit and on session switch.
	autosave_ignore_not_normal = true, -- Plugin will not save a session when no writable and listed buffers are opened.
	autosave_ignore_filetypes = { -- All buffers of these file types will be closed before the session is saved.
		"gitcommit",
	},
	autosave_only_in_session = false, -- Always autosaves session. If true, only autosaves after a session is active.
})
```

</details>

**Expected behavior**

The session with all terminal buffers is saved.

**Screenshots**

**Environment**

- OS: Ubuntu
- Desktop environment: i3wm
- Plugins commit hash: `faa769f9d568e5a0b4bace44bfcbf433424130d4`

**Additional context**

**Comment by Shatur** [comment]
Unfortunately, this is by design. `:mksession` does not save terminal buffers and you would have empty buffers in their place when you restore them. I can't do anything about it, so I close all technical buffers.

**Comment by shawnyu5** [comment]
Wait, for me if I use `:mksession` manually, it does save all buffers including the terminal buffers. If I open a `package.json` and a terminal session in another tab, and I save the session. In the `.vim` file containing the session, it does make mention of that terminal session, and does restore it upon restoring the session.

```
if bufexists("term://~/scratch/javascript//1154107:/usr/bin/zsh") | buffer term://~/scratch/javascript//1154107:/usr/bin/zsh | else | edit term://~/scratch/javascript//1154107:/usr/bin/zsh | endif
if &buftype ==# 'terminal'
  silent file term://~/scratch/javascript//1154107:/usr/bin/zsh
endif
balt term://~/scratch/javascript//1154107:/usr/bin/zsh
```

Vs a snippet from a session file with no terminal sessions, and 2 regular files

```
keepjumps exe s:l
normal! zt
keepjumps 1
normal! 0
tabnext
edit scratch.js
argglobal
balt package.json
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
```

**Comment by Shatur** [comment]
Right, I was wrong. For some reason I thought that terminal buffers aren't restorable.

**Comment by shawnyu5** [comment]
Wow, thanks for the quick fix!
