### ISSUE TITLE
Autoloads previous session

### ISSUE THREAD

**Issue by venzen** [Shatur/neovim-session-manager#26]
**Bug description**
I have the following setting for Session Manager:

`  autoload_mode = require('session_maeager.config').AutoloadMode.Disabled, `

When I start Neovim without any cmd line args, it automatically loads the previous session, implying that the `Disabled` setting has no effect - or that my config settings are not being read. However, if I put a syntax error in the config file, Nvim does complain about it.

**Steps to reproduce**

0. include the following settings in *sessionman.lua*:
```lua
local Path = require('plenary.path')
require('session_manager').setup({
  sessions_dir = Path:new(vim.fn.stdpath('./'), 'sessions'), -- The directory where the session files will be saved.
  path_replacer = '__', -- The character to which the path separator will be replaced for session files.
  colon_replacer = '++', -- The character to which the colon symbol will be replaced for session files.
  autoload_mode = require('session_maeager.config').AutoloadMode.Disabled, -- Define what to do when Neovim is started without arguments. Possible values: Disabled, CurrentDir, LastSession
  autosave_last_session = false, -- Automatically save last session on exit and on session switch.
  autosave_ignore_not_normal = true, -- Plugin will not save a session when no buffers are opened, or all of them aren't writable or listed.
  autosave_ignore_filetypes = { -- All buffers of these file types will be closed before the session is saved.
    'gitcommit',
  }, 
  autosave_only_in_session = false, -- Always autosaves session. If true, only autosaves after a session is active.
})
```
1. Start Neovim, open a few buffers, then quit nvim `:q`
2. At the cmd line: `$ nvim`
4. Previous session buffers are loaded.

**Expected behavior**
I would like to see the Alpha plugin dashboard when starting nvim without arguments.

If I disable *session-manager* and use `:PackerClean` to remove its plugin dir then the Alpha dashboard loads as expected and the previous session is not restored automatically. 

**Environment**

- Ubuntu Linux 18.02
- NVim 0.6.1

**Comment by Shatur** [comment]
Works on my machine. I think you made a typo:

```
autoload_mode = require('session_maeager.config').AutoloadMode.Disabled
```

should be:

```
autoload_mode = require('session_manager.config').AutoloadMode.Disabled,
```

**Comment by venzen** [comment]
Thank you for spotting the typo!
I also had an error in `vim.fn.stdpath('./')` - should be `vim.fn.stdpath('data')` (or `config`)
