### ISSUE TITLE
Flickering and annoying experience during opening `nvim`

### ISSUE THREAD

**Issue by MuhammadSawalhy** [Shatur/neovim-session-manager#28]
**Bug description**

When I open a directory that has a stored session, this plugin loads the session but the start window opens first. I thought that this issue comes from [startify](https://github.com/mhinz/vim-startify) plugin, but I disabled it and the issue is still happening with the default neovim start window. **[[see videos below]]**

**Steps to reproduce**

Just open a neovim in a directory with saved session 

**Expected behavior**

To sync load the session 

**Screen recordings**

![simplescreenrecorder-2022-02-20_12 07 08](https://user-images.githubusercontent.com/42011920/154995968-2e67bcaf-37bd-4bc0-82f5-8c9c0c56472f.gif)

![simplescreenrecorder-2022-02-20_12 07 52](https://user-images.githubusercontent.com/42011920/154995997-7d833e6a-c59a-4bed-8387-c03726d3de12.gif)

**Environment**

- OS: Arch Linux
```
                   -`                    ms@ms-arch
                  .o+`                   ----------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: Precision WorkStation
               `+oooooo:                 Kernel: 5.16.5-arch1-1
               -+oooooo+:                Uptime: 5 hours, 7 mins
             `/:-:++oooo+:               Packages: 786 (pacman)
            `/++++/+++++++:              Shell: zsh 5.8
           `/++++++++++++++:             Resolution: 1024x768
          `/+++ooooooooooooo/`           WM: dwm
         ./ooosssso++osssssso+`          Theme: Adwaita [GTK2/3]
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3]
       -osssssso.      :ssssssso.        Terminal: alacritty
      :osssssss/        osssso+++.       Terminal Font: Cascadia Mono
     /ossssssss/        +ssssooo/-       CPU: Intel Xeon W3550 (4) @
   `/ossssso+/:-        -:/+osssso+-     GPU: AMD ATI Radeon X1600
  `+sso+:-`                 `.-/+oso:    GPU: AMD ATI Radeon X1600 XT
 `++:.                           `-/+/   Memory: 5020MiB / 7940MiB
 .`                                 `/
```

- Plugins commit hash: 16bc2ff389fa4e6c51d5bdaee39fa308109bf3d7

**Comment by Shatur** [comment]
Not sure if it possible to fix since sessions are sourced after Neovim startup.

**Comment by MuhammadSawalhy** [comment]
I think you can block execution using so `while (session not loaded)` loop, and load the session read the status using some variable or read from a file such as `/tmp/neovim-session-manager/(random-id)`, and the `random-id` will be generated before the while loop and `session no loaded` is read from the file with this random id. When the aysnc loading is done, some text will be written in that file. 

This is just some indirect workaround that may help.

**Comment by Shatur** [comment]
No, this won't work, the problem is that Neovim is loaded first, and then the session. If you have any ideas, please send a PR.

**Comment by k1rowashere** [comment]
I have found the cause:
By removing the `vim.schedule` from `utils.load_session`, it removes the slight flicker of the intro screen. 

But this may causes a slowdown when starting vim (the entire ui waits for loading buffers and starting lazy-load plugins).
It required some tweaking to get working fast. 
Maybe it should be an option where there is a `load_startup_session` with no `vim.schedule` and docs explaining how to make it faster.

(I've used some scheduling shenanigans to get it load this fast.)
(you can take a look at [my config](github.com/k1rowashere/kiro.nvim), used a User aucmd to defer running the plugins)

[Screencast from 2024-04-30 04-26-18.webm](https://github.com/Shatur/neovim-session-manager/assets/29287159/aa2feb49-6255-4330-92a4-97bc4b6fadbd)

**Comment by Shatur** [comment]
Feel free to open a PR to update the readme.
