### ISSUE TITLE
Empty buffer.

### ISSUE THREAD

**Issue by ahmed-rezk-dev** [Shatur/neovim-session-manager#3]
When I'm opening a saved session is always open with an empty buffer. Not last windows/tabs.

**Comment by Shatur** [comment]
Dude, without steps to reproduce and minimal configuration I can't help you.

**Comment by tami5** [comment]
Dude, make it easy for other to report issues in the form you need e.g. https://github.com/nvim-telescope/telescope.nvim/blob/master/.github/ISSUE_TEMPLATE/bug_report.md.  Create file in `.github/ISSUE_TEMPLATE/bug_report.md`. Also, don't just close issues without solving them, tag them or maybe inquire for details.

Btw awesome work!

**Comment by Shatur** [comment]
> Dude, make it easy for other to report issues in the form you need

I [usually do it](https://github.com/crow-translate/crow-translate/tree/master/.github/ISSUE_TEMPLATE), but I have a lot of repos, sometimes just forgot. But I think that even without a template it should be obvious that user need to provide at least some minimal information about the problem, not just "doesn't work" :rofl:
I will reopen the issue as soon as @ahmed-rezk-dev provides information.
