### ISSUE TITLE
New AutoloadMode

### ISSUE THREAD

**Issue by rgnkn** [Shatur/neovim-session-manager#31]
**Describe the problem or limitation you are having**
With me it's basically that I nearly always specify `:SessionManager load_session`  if I open "neovim" without any file specified on the command line.

I don't want to autoload any Session as I'm working with quite a few projects and it's generally wrong to select the last session.

**Describe the solution you'd like**
I'd suggest to have a fourth Autoloadmode (~ `Select`) which automatically opens the `vim.ui.select()` for `load_session` in this instance.

**Describe alternatives you've considered**
Currently I'm solving this with a distinct function in my config but I guess it would be nice to have a builtin option for this use case.

**Additional context**
I guess this is quite generic and further context isn't necessary.

**Comment by Shatur** [comment]
Sorry, but this feature is don't follow my vision of the project.
For me last session is almost always a correct session. If it's not - I don't see any issue to call `:SessionManager load_session` from shortcut. VSCode is also have the same behavior.
I understand that you may want to have a different behavior. But you have a workaround in your config. Be hackable it's a Neovim nature.

**Comment by rgnkn** [comment]
Fair enough and as I mentioned I already have implemented this functionality in my config (while having Autoload disabled). This was more a kind of an idea.

So, I'm going to close this issue.
