### ISSUE TITLE
Conflict with tanvirtin/vgit.nvim: `The coroutine failed  with this message ... Invalid buffer id: 1`

### ISSUE THREAD

**Issue by MuhammadSawalhy** [Shatur/neovim-session-manager#36]
**Bug description**

_I'm not sure which plugin is the guilty here, so I'll open the same issue for both_: https://github.com/tanvirtin/vgit.nvim/issues/214

VGit was working well when I was using neovim `0.6.1` version but when I updated to `0.7.0` I start getting this issue only when I use [Shatur/neovim-session-manager](https://github.com/Shatur/neovim-session-manager) with VGit. for simplicity and make sure that I am right, I've used `~/.config/nvim/simple-init.vim`:

**How to start Neovim with simple configuration file:**

```
nvim -u ~/.config/nvim/simple-init.vim
```

**The simple configuration:**

```vim
let g:plug_home = '~/.config/nvim/plugins'

call plug#begin(plug_home)
Plug 'nvim-lua/plenary.nvim'
Plug 'tanvirtin/vgit.nvim'
Plug 'Shatur/neovim-session-manager'
call plug#end()

lua << EOF
require('vgit').setup()
EOF
```

**The error message:**

```
Error executing vim.schedule lua callback: ...ig/nvim/plugins/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed
 with this message: .../nvim/plugins/vgit.nvim/lua/vgit/features/LiveGutter.lua:30: Invalid buffer id: 1
stack traceback:
        [C]: in function 'error'
        ...ig/nvim/plugins/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
        ...ig/nvim/plugins/plenary.nvim/lua/plenary/async/async.lua:40: in function <...ig/nvim/plugins/plenary.nvim/lua/plenar
y/async/async.lua:39>
```

**Environment**

- nvim --version output: `NVIM v0.7.0`
- Operating system: `Arch Linux x86_64 [kernel: 5.17.1-arch1-1]`
- Desktop environment: Suckless DWM
- Plugins commit hash:
  - neovim-session-manager: [f0b0501](https://github.com/Shatur/neovim-session-manager/commit/f0b0501ed4c311adc24fa00f27f17694faeb36a9)
  - vgit: [9a2ef0b](https://github.com/tanvirtin/vgit.nvim/commit/9a2ef0b0edede4dcf35cc53801eed4c7cdd15605)

**Comment by Shatur** [comment]
I think that the issue is on VGit side. When I loading session, I remove all old buffers and VGit should be able to restore it's state after buffers cleanup. Here is the code which is responsible for it:

https://github.com/Shatur/neovim-session-manager/blob/f0b0501ed4c311adc24fa00f27f17694faeb36a9/lua/session_manager/utils.lua#L51-L58

I had a similar issue with nvim-scroll: https://github.com/dstein64/nvim-scrollview/issues/70

**Comment by nyngwang** [comment]
@MuhammadSawalhy:

You can use my plugin as a temporary fix: https://github.com/nyngwang/NeoNoName.lua. Add this to your config file:

```lua
vim.cmd([[
  augroup VGitFix
    au!
    au VimEnter * NeoNoNameClean
  augroup END
]])
```

**Comment by nyngwang** [comment]
@MuhammadSawalhy: FYI: the method in my previous comment doesn't work now :(

**Comment by MuhammadSawalhy** [comment]
This issue doesn't happen anymore. I think somewhere the bug was fixed in NeoVim or either of the plugins.
