### ISSUE TITLE
Where does it actually save the sessions? vim.fn.stdpath('data'), 'sessions')?

### ISSUE THREAD

**Issue by thepenguinthatwants** [Shatur/neovim-session-manager#38]
Hi,
I find this plugin working quite greatly. But the problem is that it considers way too many location as session.
Thus I added this     

`autoload_mode = require('session_manager.config').AutoloadMode.Disabled, -- Define what to do when Neovim is started without arguments. Possible values: Disabled, CurrentDir, LastSession`

But I am unsure where is the physical location for sessions?
`    sessions_dir = Path:new(vim.fn.stdpath('data'), 'sessions'), -- The directory where the session files will be saved.`
This works but I cant seem to find the files? As I want to clean obsolete ones.

**Comment by Shatur** [comment]
Take a look at `:h stdpath`.
