### ISSUE TITLE
Internal error when opening sessions

### ISSUE THREAD

**Issue by nullishamy** [Shatur/neovim-session-manager#47]
**Bug description**
When opening a session, session-manager errors internally. The plugin still works fine, though the error is displayed.

**Steps to reproduce**
- Open nvim
- Open a session
- Observe the error ouput

<details><summary>Minimal configuration</summary>

```lua
require('session_manager').setup({
})
```
</details>

**Expected behavior**
The plugin does not error

**Screenshots**

**Environment**

- OS: Arch
- Desktop environment: i3
- Plugins commit hash:  7267e396e00b41cd038f818f36eddf772b39c8b2

**Additional context**
```
Error executing vim.schedule lua callback: ...art/neovim-session-manager/lua/session_manager/utils.lua:63: Vim(set):E591: 'winheight' cannot be smaller than 'winminheight'
: winheight=1                                                                                                                                                              
stack traceback:                                                                                                                                                           
        [C]: in function 'nvim_command'                                                                                                                                    
        ...art/neovim-session-manager/lua/session_manager/utils.lua:63: in function <...art/neovim-session-manager/lua/session_manager/utils.lua:52>
        ```

**Comment by Shatur** [comment]
> Error executing vim.schedule lua callback: ...art/neovim-session-manager/lua/session_manager/utils.lua:63: Vim(set):E591: 'winheight' cannot be smaller than 'winminheight'

This line refers to the following line: 

https://github.com/Shatur/neovim-session-manager/blob/7267e396e00b41cd038f818f36eddf772b39c8b2/lua/session_manager/utils.lua#L87

Which just source your session. I assume that you configured 'winheight' smaller than 'winminheight' in your configuration or in the session locally. And the error says that you should fix this setting.

**Comment by nullishamy** [comment]
I don't recall setting an explicit value for that, what sort of value could i try setting to see if it works? I will double check my config to make sure that its not set.

**Comment by Shatur** [comment]
> I don't recall setting an explicit value for that, what sort of value could i try setting to see if it works?

Just open the saved session and see what value is explicitly set.

**Comment by Shatur** [comment]
> Checked, it's not set.

If you haven't set any values ​​in your config, then this may be caused by some plugin that does.

**Comment by nullishamy** [comment]
```vim
set winheight=24 winwidth=116
```

Here's what's set in the saved config.

**Comment by nullishamy** [comment]
Thanks, seems that focus.nvim was setting the option. I'll see what i can do to fix it.

**Comment by nullishamy** [comment]
For any future readers, setting the following [lua] config option resolves the issue:
```lua
vim.g.sessionoptions = 'blank,buffers,curdir,folds,help,tabpages'
```

**Comment by xzbdmw** [comment]
this command finally get focus.nvim to work 
```lua
vim.cmd("set sessionoptions=blank,buffers,curdir,help,tabpages")
```
