### ISSUE TITLE
Incorrect instruction for using the telescope extension in README

### ISSUE THREAD

**Issue by AndreAugustoAAQ** [Shatur/neovim-session-manager#5]
**Bug description**
Currently, the extension usage instruction in Telescope is incorrect.
In the README, the statement is `require('telescope').load_extension('session_manager')`, causing an error to occur because the file in `lua/telescope/_extensions` is named `sessions.lua`, which should be `session_manager.lua` to join in accordance with README, or README using `sessions` in the extension load

Using `require('telescope').load_extension('sessions')` works correctly

**Steps to reproduce**
Just start already presents the plugin error that does not exist due to the fact presented

<details><summary>Minimal configuration</summary>
require("packer").startup({function()
		use({
			{ "wbthomason/packer.nvim", opt = true },
			{ "nvim-telescope/telescope.nvim", requires = { "nvim-lua/plenary.nvim" } },
			{ "Shatur/neovim-session-manager", requires = { "nvim-telescope/telescope.nvim" } },
		})
	end,
})

require("telescope").load_extension("session_manager")

</details>
**Environment**

- OS: Windows 10 20H2
- Plugins commit hash: 88a43e68fd8cc9a448192fcf7f275a13c1e7f2fd

**Comment by Shatur** [comment]
Thanks, just forgot to update the readme.

**Comment by venzen** [comment]
I assume that loading `session_manager` as a Telescope extension has been replaced with using `telescope-ui-select`? 

1. Except for installing and loading the `ui-select` plugin, is there any command or code required to then use Telescope?
2. The ability to limit Telescope search/find/grep to a specific directory is very appealing. Is there an easy way to configure this for the current session directory?

**Comment by Shatur** [comment]
> I assume that loading session_manager as a Telescope extension has been replaced with using telescope-ui-select

Yes.

> Except for installing and loading the ui-select plugin, is there any command or code required to then use Telescope?

No.

> The ability to limit Telescope search/find/grep to a specific directory is very appealing. Is there an easy way to configure this for the current session directory?

No, but there was another plugin that have this feature (don't remember the name).

**Comment by venzen** [comment]
> > The ability to limit Telescope search/find/grep to a specific directory is very appealing. Is there an easy way to configure this for the current session directory?
> 
> No, but there was another plugin that have this feature (don't remember the name).

I first noticed this useful Telescope feature in `telescope-project` plugin, but I changed to `nvim-session-manager` because this plugin's feature of managing session state is preferable to the `project` plugin management of directory location. 

Limiting telescope to a specific location is great. I'm sticking with `session-manager` and will continue searching for how to make a telescope do that.

**Comment by Shatur** [comment]
> EDIT - reading the Telescope page, most of the pickers, including find_files, live_grep, git_files, etc operate in the current working directory. No special params needed. So, neovim-session-manager does what I need.

Oh, sorry, I misread. Yes, this is how it works by default.
