### ISSUE TITLE
`Attempt to index a nil value` on session restore

### ISSUE THREAD

**Issue by shawnyu5** [Shatur/neovim-session-manager#51]
**Bug description**

When opening neovim in a directory with a session associated with it. And the session manager tries to store the session, the following error pops up. Once the error is dismissed, the session gets restored successfully

![image](https://user-images.githubusercontent.com/55592708/184269145-9aade129-b55e-4fb8-884a-e279fac2ec6c.png)

**Steps to reproduce**

<details><summary>Minimal configuration</summary>
Install this plugin

```lua
require("session_manager").setup({
	sessions_dir = Path:new(vim.fn.stdpath("data"), "sessions"), -- The directory where the session files will be saved.
	path_replacer = "__", -- The character to which the path separator will be replaced for session files.
	colon_replacer = "++", -- The character to which the colon symbol will be replaced for session files.
	autoload_mode = require("session_manager.config").AutoloadMode.CurrentDir,
	-- Define what to do when Neovim is started without arguments. Possible
	-- values: Disabled, CurrentDir, LastSession
	autosave_last_session = false, -- Automatically save last session on exit and on session switch.
	autosave_ignore_not_normal = true, -- Plugin will not save a session when no writable and listed buffers are opened.
	autosave_ignore_filetypes = { -- All buffers of these file types will be closed before the session is saved.
		"gitcommit",
	},
	autosave_only_in_session = false, -- Always autosaves session. If true, only autosaves after a session is active.
})
```
</details>

1. Go to a directory, open a few files in neovim. And run `:SessionManager save_current_session`
2. Close neovim, and reopen neovim.

**Expected behavior**

The session should restore with no error

**Screenshots**

**Environment**

- OS:  Arch
- Desktop environment:  i3
- Plugins commit hash:  6604857365b13bfbcaa7ef377d4e60d2acb0be02

Neovim version: 

```
NVIM v0.8.0-dev-809-gb4b22318a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Additional context**

**Comment by Shatur** [comment]
Can't reproduce on my machine.
By looking at the error I would say that the issue in the LSP server.

**Comment by shawnyu5** [comment]
Yeah the error seems to pop up in other places as well, not just when the session manager restores a session. Seems like a neovim nighly issue. Going to close this.
