### ISSUE TITLE
Close a session?

### ISSUE THREAD

**Issue by ceuk** [Shatur/neovim-session-manager#65]
Is there a way to close a session (i.e. destroy all active buffers, close all tabs except the first, clear all transient settings etc). Essentially emulating closing vim and re-opening it.

(Similar to Startify's `SessionClose` cmd)

**Comment by Shatur** [comment]
I don't like the idea. It basically the same as close all tabs and buffers. You can use any plugin for buffer / tab management for it.

**Comment by ceuk** [comment]
Okay, say I am in the middle of some session and I want to cd into a new folder for the first time and create a session in there. 

How would I do that without polluting the new session with buffers etc from the current session? Is the canonical approach with this plugin to close down all buffers etc manually first?

**Comment by hinell** [comment]
You tried to delete the `Session.vim`&

**Comment by hinell** [comment]
You tried to delete the `Session.vim`?

**Comment by Shatur** [comment]
There are a lot of plugins for deleting all buffers.
