### ISSUE TITLE
Is it possible to auto save a session with git branch name?

### ISSUE THREAD

**Issue by ruanyl** [Shatur/neovim-session-manager#67]
**Describe the problem or limitation you are having**
When switching git branches and starting to work on a new feature, the session restored with the previous opened files. This is frustrating if switching branches frequently.

**Describe the solution you'd like**
Perhaps there can be a custom configuration that allows user to auto save a session with branch name?

**Comment by Shatur** [comment]
#64 should add this use case.

**Comment by lougreenwood** [comment]
Looks like Extendable extras was merged to master, not sure if it's released though?

@Shatur Can you point to a config using the extendable extras to enable per-git-branch sessions?

I guess something like https://github.com/Shatur/neovim-session-manager/pull/45 could also solve the issue, but that seems stuck?

**Comment by Shatur** [comment]
Oh, I just forgot to close the issue :) It's available, you can use it. See the linked PR, I just changed the API a little bit.
