### ISSUE TITLE
feature: remap `delete_session`

### ISSUE THREAD

**Issue by vxio** [Shatur/neovim-session-manager#7]
**Describe the solution you'd like**

The ability to remap `delete_session`. Currently it defaults to
```
map('n', 'd', delete_session, { nowait = true })
```
but there is no way to change it.

**Comment by Shatur** [comment]
Makes sense. How would you like it to look?

**Comment by Shatur** [comment]
`delete_session` is telescope specific. I think we should somehow allow users to redefine it via Telescope settings. Like you can do with standard actions. Here is [an example](https://github.com/Shatur/neovim-config/blob/9c78f230723c88d4adeafa67ed7f7942e922a630/plugin/telescope.lua#L45) from my configuration.

But I don't know how to implement it this way. So help is appreciated.

**Comment by Shatur** [comment]
I decided to migrate to `vim.ui.select()` and I can no longer provide session deletion at all. But I don't think it makes sense. It is not very convenient and I do not think that anyone used it at all.
Let's see if someone will need it, I think we could add a separate command for session deletion. It's just not possible to support `vim.ui.select()` and custom mapping.
