### ISSUE TITLE
Current working directory changed if `vim.opt.shellslash = true` on windows.

### ISSUE THREAD

**Issue by ysl2** [Shatur/neovim-session-manager#70]
On windows.

if I set `vim.opt.shellslash` to true, and toggle nvim-tree, the current directory will be changed.

**Comment by Shatur** [comment]
Wrong repo? You probably wanted to report it to https://github.com/nvim-tree/nvim-tree.lua

**Comment by Shatur** [comment]
We change current directory only on session load.
