### ISSUE TITLE
Opening session with swap file results in error

### ISSUE THREAD

**Issue by Subjective** [Shatur/neovim-session-manager#72]
**Bug description**

Opening a session with a swap file that already exists results in an error after selecting any of the choices brought up by the swap file prompt. This usually happens when one of the files in the session is already open in another editor.

**Steps to reproduce**

<details>
<summary>Minimal configuration</summary>
<br>

```lua
require("session_manager").setup({})
```
</details>

**Expected behavior**
 Session opens normally without throwing error upon selecting one of the options brought up by the swap file prompt.

**Screenshots**

![image](https://user-images.githubusercontent.com/56745535/222943308-8d9ee7d0-a407-4e6b-a824-b3c333234932.png)
![image](https://user-images.githubusercontent.com/56745535/222943328-f2f50a12-7440-4a1f-9726-83938183acae.png)
**Environment**
- OS:  MacOS Ventura
- Desktop environment:  i9-9980HK, AMD Radeon Pro 5550M
- Plugins commit hash:  e7a2cbf56b5fd3a223f2774b535499fc62eca6ef

**Additional context**

```
Error executing vim.schedule lua callback: ...azy/neovim-session-manager/lua/session_manager/utils.lua:82: /Users/joshua/.local/share/nvim/sessions/__U
sers__joshua__.config__nvim, line 19: Vim(edit):E325: ATTENTION
stack traceback:
        [C]: in function 'nvim_command'
        ...azy/neovim-session-manager/lua/session_manager/utils.lua:82: in function <...azy/neovim-session-manager/lua/session_manager/utils.lua:70>
```

**Comment by Shatur** [comment]
Looks like it fails on this command:
```lua
vim.api.nvim_command('silent source ' .. filename)
```
Probably happens because after sourcing if facing a swap message. Not sure how to avoid it.
Could you try to source a session file with swap manually and see if you have the same error?

**Comment by tobealive** [comment]
> ```lua
> vim.api.nvim_command('silent source ' .. filename)
> ```

An error traceback without using a swapfile leads me to the same line.

```
Error executing vim.schedule lua callback: ...azy/neovim-session-manager/lua/session_manager/utils.lua:82: /home/turiiya/.local/share/nvim/sessions/__home__turiiya__Dev__vlang__bartender, line 48: Vim(bwipeout):E517: No buffers were wiped out: bwipe 19
stack traceback:
	[C]: in function 'nvim_command'
	...azy/neovim-session-manager/lua/session_manager/utils.lua:82: in function <...azy/neovim-session-manager/lua/session_manager/utils.lua:70>
```

Got this since moving from bufferline to barbar. But it doesn't seem to be a barbar issue

**Comment by tobealive** [comment]
```lua
vim.cmd('silent source ' .. filename)
```

Randomly checked. This makes no issues. May I PR?

**Comment by Shatur** [comment]
Do I undersntad correctly that changing `nvim_command` into `cmd` fixed your issue?
If yes, I think it's a coincidence. I think that there was something nasty in your session that caused crash. It's not related to the session manager.

**Comment by tobealive** [comment]
It really seems random that this fixes it. The difference in those commands is so marginal that if one errors the other should too. I might have been a bit to hasty with my comment. 

Since I'm getting the error all the time I'll clear all my sessions and use `api.nvim_command` for half a day and `vim.cmd` for the other half. If it really makes a difference.

**Comment by Subjective** [comment]
Recently I stumbled upon a similar issue with Mini.Sessions (echasnovski/mini.nvim#75), and it seems like they were able to fix it by replacing `silent source` with `silent! source`. This also seems to resolve the issue for neovim-session-manager as well.

**Comment by Shatur** [comment]
@Subjective Sorry, missed the message. Unfortunately, it will just silence the error. The same way you can just `vim.o.swapfile = false` in your config.
Instead I think we should just ignore `ATTENTION` error kinds when source.

**Comment by Zeioth** [comment]
I can reproduce
![screenshot_2023-06-03_22-24-45_605957776](https://github.com/Shatur/neovim-session-manager/assets/3357792/70256e37-7a50-47b7-adb3-45183b9683dc)

**Comment by Zeioth** [comment]
PR #83 seems to silence the error without causing any side effect. But I imagine it could make harder debugging possible future issues.

Using Zeioth/neovim-session-manager in the meantime.

**Comment by Shatur** [comment]
As a workaround you can set `vim.o.swapfile = false`.

**Comment by Shatur** [comment]
Wondering if we can set it temporarily while loading session... Is the issue happen only after autoload?

**Comment by Zeioth** [comment]
To me, only happen in the moment of trying to load a saved session.

**Comment by Shatur** [comment]
Could you try #89?
