### ISSUE TITLE
Error occurs when configuring to Save session on save buffer

### ISSUE THREAD

**Issue by jordan-bravo** [Shatur/neovim-session-manager#73]
**Bug description**

I followed the README section on [Save session on save buffer](https://github.com/Shatur/neovim-session-manager#save-session-on-save-buffer), but the following error occurs when saving the configuration:

```
Error detected while processing BufWritePost Autocommands for "*":                                                                          
Error executing lua callback: [string "..."]:0: attempt to index global 'session_manager' (a nil value)
```

Additionally, the diagnostic text shows an error `Undefined global `session_manager`.  See screenshot:

![Screenshot 2023-03-07 at 12 42 12](https://user-images.githubusercontent.com/62706808/223504709-3abea5ba-3784-4095-af26-1434d5989c64.png)

Setup config:

![Screenshot 2023-03-07 at 12 44 35](https://user-images.githubusercontent.com/62706808/223505400-2b2afb11-8007-4cfb-8588-ca7a87cbf790.png)

**Steps to reproduce**

1. Starting with base configuration of LunarVim.
2. Open `config.lua` and add plugin `neovim-session-manager`  as shown in the [README](https://github.com/Shatur/neovim-session-manager#configuration).
3. Add configuration to have NvimTree automatically opened after a session load.
4. Save `config.lua`.  At this point, `neovim-session-manager` is working as expected.
5. Open `config.lua` and add configuration to Save session on save buffer as shown in the [README](https://github.com/Shatur/neovim-session-manager#save-session-on-save-buffer)
6. Save `config.lua`.
7. Error occurs.

**Expected behavior**
Configuration should save without errors.

**Environment**

- OS: MacOS Ventura 13.2.1
- Plugins commit hash: `master`

**Comment by Shatur** [comment]
> Error executing lua callback: [string "..."]:0: attempt to index global 'session_manager' (a nil value)

You need to `require('session_manager')` somewhere first.

**Comment by jordan-bravo** [comment]
For anyone else reading this, I solved it with the following config (added line 38):

![Screenshot 2023-03-08 at 14 02 04](https://user-images.githubusercontent.com/62706808/223811110-9bb7b78a-4403-484d-a9e6-3beff6f81288.png)

@Shatur , thank you for your help. 😃
