### ISSUE TITLE
AutoloadMod.CurrentDir Wrong Cursor Placement

### ISSUE THREAD

**Issue by guydelarea** [Shatur/neovim-session-manager#74]
**Bug description**

In AutoloadMod.CurrentDir  the session is loaded successfully  but the cursor is at the top of the file (line number 2 for some reason)
when i manually run the command SessionManager load_current_dir_session the cursor jump back to right location (saved location) 

**Environment**

- OS:  Windows 11 (WSL 2)
- Desktop environment:  WSL-2 Ubuntu 22.04 | 5.10.16.3-microsoft-standard-WSL2

Default plugin config

**Comment by Shatur** [comment]
Hi! I don't have this issue... I believe it could be caused by a plugin.

**Comment by guydelarea** [comment]
Yep, caused by https://github.com/startup-nvim/startup.nvim (Dashboard)
Thanks!
