### ISSUE TITLE
Error when loading a session

### ISSUE THREAD

**Issue by svanharmelen** [Shatur/neovim-session-manager#75]
**Bug description**
After updating my plugins yesterday (which I do almost daily) I get this error when loading a session:

```
Error executing vim.schedule lua callback: ...art/neovim-session-manager/lua/session_manager/utils.lua:82: Vim(append):Error executing lua callback: ...elen/.config/nvim/lua/plugins/neovim-session-manager.lua:19: attempt to call field 'find_file' (a nil value)
stack traceback:
        ...elen/.config/nvim/lua/plugins/neovim-session-manager.lua:19: in function <...elen/.config/nvim/lua/plugins/neovim-session-manager.lua:17>
        [C]: in function 'nvim_command'
        ...art/neovim-session-manager/lua/session_manager/utils.lua:82: in function <...art/neovim-session-manager/lua/session_manager/utils.lua:70>
stack traceback:
        [C]: in function 'nvim_command'
        ...art/neovim-session-manager/lua/session_manager/utils.lua:82: in function <...art/neovim-session-manager/lua/session_manager/utils.lua:70>
```

**Steps to reproduce**

Just open a saved session...

**Expected behavior**
I would expect the session to open without error. Yet after I`enter` the error away, the session does seem to be loaded.

**Screenshots**
<img width="1838" alt="image" src="https://user-images.githubusercontent.com/4171547/224942443-6ace2986-5e30-4d0a-991e-01304199bb4a.png">

**Environment**

- OS: macOS Ventura
- Plugins commit hash: e7a2cbf56b5fd3a223f2774b535499fc62eca6ef

**Comment by Shatur** [comment]
Looks like the issue caused by your configuration. Specially file `~/.config/nvim/lua/plugins/neovim-session-manager.lua` in line 19.

**Comment by svanharmelen** [comment]
Think your right, thanks for the pointer I somehow missed that!
