### ISSUE TITLE
load_current_dir_session incorrectly loads last session

### ISSUE THREAD

**Issue by Subjective** [Shatur/neovim-session-manager#78]
**Bug description**

Running `nvim "+SessionManager load_current_dir_session"` from the shell loads the last session instead of the session associated with the current working directory.  

**Steps to reproduce**

<details>
<summary>Minimal configuration</summary>

```lua
{
  "Shatur/neovim-session-manager"
}
```

</details>

1. cd into a directory
2. launch neovim and load session
3. exit neovim and cd into another directory
4. run nvim "+SessionManager load_current_dir_session"

**Expected behavior**
I expected neovim open the session associated with the cwd of the parent shell, not the last session.

**Screenshots**

![Screen Recording 2023-04-11 at 12 38 23 AM](https://user-images.githubusercontent.com/56745535/231093777-d25c3f35-e9ca-4c2a-873d-22462b1bc0fa.gif)

**Environment**

- OS: MacOS Ventura 13.3
- Plugins commit hash: d1883f30921193f3cff4537e27514e454e0331e9

**Additional context**

There are two main use cases I have for this: 1) I'd like to set this to a convenient alias to quickly open the neovim session associated with any working directory from the terminal, and 2) I can have tmux resurrect restore the correct neovim sessions associated with each split/window's cwd after restarting tmux. Thanks.

**Comment by Shatur** [comment]
I think it happens because you have `autoload_mode` set to `require('session_manager.config').AutoloadMode.LastSession`

**Comment by Subjective** [comment]
That seems to have fixed it, thanks! Any idea why it doesn't matter what arguments are passed in? I thought the arguments would have to be one of the following: `load_session`, `load_last_session`, `load_current_dir_session`, `save_current_session`, `delete_session`, but that doesn't seem to be the case. 

![Screen Recording 2023-04-11 at 2 31 37 AM](https://user-images.githubusercontent.com/56745535/231118861-c273a721-4c12-4e2c-a1a5-c7a9306d00ad.gif)

Passing in no arguments throws an error:
![Screen Recording 2023-04-11 at 2 38 03 AM](https://user-images.githubusercontent.com/56745535/231120351-fe1d6b84-d43c-4435-bccb-8d25fc791ba8.gif)
