### ISSUE TITLE
Loading session with tabs restores all buffers to the first tab

### ISSUE THREAD

**Issue by lougreenwood** [Shatur/neovim-session-manager#79]
After upgrading to Neovim 0.9 & upgrading my Nvim distort (Astronvim 3.x) I've noticed that when I restore a session where I had multiple tabs the first tab will now have all of the open buffers.

Because I upgraded multiple things at once, I don't know if this is a bug in this project, Neovim 0.9 or Astronvim 3.x.

I'll try to see if I can isolate it to either the distro or nvim 0.9 and report back.

**Comment by Shatur** [comment]
Hi! I also upgraded to 0.9, but don't have this issue. So probably something with your other plugins.
