### ISSUE TITLE
Feature request: Open the action selection menu on `:SessionManager` without arguments

### ISSUE THREAD

**Issue by mchekardov** [Shatur/neovim-session-manager#87]
I think it would be a nice addition to the plugin
![Concept](https://github.com/Shatur/neovim-session-manager/assets/87815870/4522fe9c-6410-4b49-ab37-3d57c0fd295b)

**Comment by CleoMenezesJr** [comment]
Yes, please!

**Comment by CleoMenezesJr** [comment]
It would be nice if this were an extension to Telescope where you had some keybindings so that when you have the cursor on one of the sessions, the action was performed on it.

**Comment by shaeinst** [comment]
this issue can be closed now #109
