### ISSUE TITLE
Issues with alpha-vim, "only floating window will remain"

### ISSUE THREAD

**Issue by nyonson** [Shatur/neovim-session-manager#88]
**Bug description**

I use neovim-session manager with alpha-vim and recently been seeing the following when I try to load a session:

```
Error executing vim.schedule lua callback: ...art/neovim-session-manager/lua/session_manager/utils.lua:82: /home/.local/share/nvim/sessions/__home__njohnson__dts, line 4: Vim(only):E5601: Cannot clos
e window, only floating window would remain
stack traceback:
        [C]: in function 'nvim_command'
        ...art/neovim-session-manager/lua/session_manager/utils.lua:82: in function <...art/neovim-session-manager/lua/session_manager/utils.lua:70>
```

I am running `:SessionManager! load_session<CR>` with alpha. I noticed things work without the `!`, but then I have to tell it to not save the alpha session which is annoying. Not sure what changed between neovim, alpha, and session-manager though.

**Comment by Shatur** [comment]
Looks like alpha-vim spawns an editable window?

**Comment by nyonson** [comment]
I am not sure to be honest, but out of my element here. Trying to learn and track down what changed though.

**Comment by Shatur** [comment]
Could you check if `:% bd!` also reproduces the issue?

**Comment by nyonson** [comment]
That reports 2 buffers are deleted and alpha closes. The same crash does not occur.

**Comment by nyonson** [comment]
Hm, so I just gave it a shot again with `:SessionManager! load_session<CR>` and it now works fine...I haven't been messing with my configs, but maybe something updated? I'd be happy to run any more tests if you like, or if you just want to ignore this as noise that is fine too!

**Comment by Shatur** [comment]
Judging by the error message the issue happens because you have an edited floating window somewhere. It shouldn't happen, probably an issue of some other pluging, not sure.

**Comment by nyonson** [comment]
I'll try to track it down and leave a note here if I do, but in any case, thanks for the pointers.
