### ISSUE TITLE
Bug: `autosave_only_in_session = false` doesn't work as expected

### ISSUE THREAD

**Issue by Zeioth** [Shatur/neovim-session-manager#91]
**Describe the problem or limitation you are having**
Once a session is automatically created, there is no way to override the session when saving another file of the same directory, unless we have previously opened the existing session. For example image we have:

```
MyDir
  * file1
  * file2
```

If I open and write file1, the session will be created. But if then I open and write file2, the session won't be re-created. The only way to modify the session would be opening it and then change it.

**Describe the solution you'd like**
Having the method `session_manager.delete_current_session()` to delete any existing session of the current directory, we could ensure every time a user changes a file in a directory, the existing session is overrided and re-created like:

```lua
vim.api.nvim_create_autocmd({ 'BufWritePost' }, {
  group = config_group,
  callback = function ()
    if vim.bo.filetype ~= 'git'
      and not vim.bo.filetype ~= 'gitcommit'
      and not vim.bo.filetype ~= 'gitrebase'
      then 
            session_manager.delete_current_session()
            session_manager.save_current_session()
      end
  end
})
```

**Comment by Zeioth** [comment]
I've noticed there is an option for this, but it doesn't seem to be working correctly. Having `autosave_only_in_session` doesn't do anything.

```lua
  {
    "Shatur/neovim-session-manager",
    cmd = "SessionManager",
    opts = {
      autosave_last_session = true, -- Automatically save last session on exit and on session switch.
      autosave_only_in_session = false
    },
    config = function(opts)
      local session_manager = require('session_manager')
      session_manager.setup(opts)

      -- Auto save session when saving a buffer
      -- This ensures the auto saved session is up to date.
      local augroup = vim.api.nvim_create_augroup
      local autocmd = vim.api.nvim_create_autocmd
      autocmd({ 'BufWritePre' }, {
        group = augroup("session_manager_autosave_on_write", { clear = true }),
        callback = function ()
            session_manager.save_current_session()
        end
      })
    end
  },
```

**Comment by Shatur** [comment]
> Once a session is automatically created, there is no way to override the session when saving another file of the same directory, unless we have previously opened the existing session. 

I don't get it. By default session is automatically saved and it overrides the previous one.

**Comment by Zeioth** [comment]
For some reason it doesn't do it on my end. I'll try to figure out why.

**Comment by Zeioth** [comment]
I can't believe I made such a rocky mistake: I was not properly loading the plugin at startup. Using `lazy = false` now everything works as expected.

```
  {
    "Shatur/neovim-session-manager",
    lazy = false,
    cmd = "SessionManager",
    opts = {
      autoload_mode = require('session_manager.config').AutoloadMode.Disabled, -- Do not autoload on startup
      autosave_last_session = true,
      autosave_only_in_session = false
    },
    config = function(_, opts)
      local session_manager = require('session_manager')
      session_manager.setup(opts)

      -- Auto save session when saving a buffer
      -- This ensures the auto saved session is up to date.
      local augroup = vim.api.nvim_create_augroup
      local autocmd = vim.api.nvim_create_autocmd
      autocmd({ 'BufWrite' }, {
        group = augroup("session_manager_autosave_on_write", { clear = true }),
        callback = function ()
            print("event triggered")
            session_manager.autosave_session()
        end
      })
    end
  },
```

Closing issue and apologies for the inconvenience.
